name: Auto CL update

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  post_merge_job:
    name: Auto CL update
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull latest changes for update-changelog branch
      run: |
        git fetch origin
        git checkout -b update-changelog || git checkout update-changelog

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install requirements
      run: pip install aiohttp pyyaml

    - name: Run post-merge script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python Tools/_Europa/autoCL/auto_cl.py "${{ secrets.PAT_CL_TOKEN }}" "${{ github.repository }}"

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit changes
      id: commit-changes
      run: |
        git add .
        git diff-index --quiet HEAD || git commit -m "Auto cl update"
      continue-on-error: true

    - name: Push changes to a new branch
      if: steps.commit-changes.outcome == 'success'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} update-changelog --force

    - name: Create Pull Request
      if: steps.commit-changes.outcome == 'success'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: master
        branch: update-changelog
        commit-message: "Auto CL update"
        title: "Auto CL update"
        body: "No CL, no fun"
        labels: "auto-update changelog"
      continue-on-error: true
